# Generated by Django 5.0.1 on 2024-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_language_number_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='number_id',
        ),
        migrations.AddField(
            model_name='city',
            name='number_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='номер в списке'),
        ),
    ]
